version: 0.2
env:
  variables:
    BUILD_SPEC: 'build'
    AWS_PRIVATE_ECR: '489478819445.dkr.ecr.ap-northeast-2.amazonaws.com'

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:

  pre_build:
    commands:
      - echo "#### src_dir:${CODEBUILD_SRC_DIR}"
      - docker login --username AWS -p $(aws ecr get-login-password --region ap-northeast-2) ${AWS_PRIVATE_ECR}
      - docker pull ${AWS_PRIVATE_ECR}/amazoncorretto:11 || true
    finally:

  build:
    commands:
      - echo "Artifact for build" > build_output.txt
      - mkdir ${CODEBUILD_SRC_DIR}/gradle_home
      - export GRADLE_USER_HOME=${CODEBUILD_SRC_DIR}/gradle_home
      - |
        echo "Build Accounting-Statements module."
        chmod +x ./gradlew
        ./gradlew clean build -x test --no-daemon
    finally:

artifacts:
  files:
    - build_output.txt
    - ./build/**/*
    - ./gradle_home/**/*
    - ./.gradle/**/*
