version: 0.2
env:
  variables:
    BUILD_SPEC: 'test'
phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - npm install -g aws-cdk@1.75.0
  build:
    commands:
      - echo "Artifact for deploy" > deploy_output.txt
artifacts:
  files:
    - deploy_output.txt